### ISSUE TITLE
Update to astro.build 1.0

### ISSUE THREAD

**Issue by blackgwe** [matthewp/astro-lit-demo#1]
Hi, 

Thanks for the work. Do you think it's possible to get shoelace.style running with astro v1.0.6 (with or without your renderer)?

Best regards,
Gabriel

**Comment by blackgwe** [comment]
Got an error
```
 generating static routes
▶ src/pages/index.astro
 error   t._$AK is not a function
    at _$AK (file:///private/tmp/astro-lit-demo/node_modules/lit-element/lit-element.js:6:907)
    at LitElementRenderer.attributeChangedCallback (file:///private/tmp/astro-lit-demo/node_modules/@lit-labs/ssr/lib/lit-element-renderer.js:34:9)
    at LitElementRenderer.setAttribute (file:///private/tmp/astro-lit-demo/node_modules/@lit-labs/ssr/lib/element-renderer.js:72:18)
    at render (file:///private/tmp/astro-lit-demo/node_modules/@astrojs/lit/server.js:44:14)
    at render.next (<anonymous>)
    at Object.renderToStaticMarkup (file:///private/tmp/astro-lit-demo/node_modules/@astrojs/lit/server.js:76:11)
    at renderComponent (file:///private/tmp/astro-lit-demo/dist/entry.mjs?time=1660836220278:838:66)
```
